#!/usr/bin/perl
#
# collect some simple stats from an input file
#

my (@vs, $avg, $min, $max, $sum, $nlogn);

$_ = <STDIN>;
chomp;
$min = $max = $sum = $_;
push(@vs, $_);

while (<STDIN>) {
    chomp;

    $sum += $_;
    $min = $_ if $_ < $min;
    $max = $_ if $_ > $max;
    push(@vs, $_);
}

$avg = int($sum / @vs);
$sum = 0;
$sum += abs($avg - $_) for @vs;
$nlogn = $ARGV[0] * log($ARGV[0]) / log(2);

printf("avg %u (%.2f nlogn)\n", $avg, $avg / $nlogn);
printf("std dev %u\n", $sum / @vs);
printf("max %u\n", $max);
printf("min %u\n", $min);

@vs = sort {$a <=> $b} (@vs);
printf("median %u\n", $vs[@vs / 2]);
